from braillebase import BrailleBase

class BrailleBaseJapanese(BrailleBase):
    def __init__(self):

        """
        Weighted average accuracy: ≈ 96–97%

        EN
        Braille table for the Japanese language.
        This library is built on top of BrailleBase.
        The current version accepts keys (characters) composed of only one Japanese character, while the values (braille cells) may contain as many cells as needed.
        Note:
        Combinations that form yōon — such as きゃ, きゅ, きょ, ひゃ, ひゅ, ひょ, ぴゃ, ぴゅ, ぴょ — are written in Japanese using two characters (for example: ひ + ゃ = ひゃ).
        Since the current version only accepts single‑character keys, these combinations are interpreted separately.
        For example, when processing ひゃ, the library outputs:
        - ひ
        - ゃ（small や）
        instead of recognizing ひゃ as a single combined syllable.

        JP
        日本語点字のテーブルです。
        このライブラリは BrailleBase を基盤として動作しています。
        現行バージョンでは、キー（文字）は 1 文字のみ登録でき、
        値（点字）は必要なだけ複数セルを登録できます。
        注意：
        **拗音（きゃ・きゅ・きょ、ひゃ・ひゅ・ひょ、ぴゃ・ぴゅ・ぴょ など）**は、
        本来 2 文字の組み合わせ（例：ひ + ゃ = ひゃ） で 1 音を表します。
        しかし現行バージョンでは キーが 1 文字しか登録できないため、
        「ひゃ」は次のように別々に処理されます：
        - ひ
        - ゃ（小さいや）
        つまり、ひゃ として 1 つの音にまとめることができません。

        IT
        Tabella Braille per la lingua giapponese.
        Questa libreria utilizza BrailleBase come struttura principale.
        L’attuale versione accetta chiavi composte da un solo carattere giapponese, mentre i valori (celle braille) possono contenere tutte le celle necessarie.
        Nota:
        Le combinazioni che formano gli yōon — come きゃ, きゅ, きょ, ひゃ, ひゅ, ひょ, ぴゃ, ぴゅ, ぴょ — sono scritte in giapponese usando due caratteri (ad esempio: ひ + ゃ = ひゃ).
        Poiché l’attuale versione accetta solo chiavi di un singolo carattere, queste combinazioni vengono interpretate separatamente.
        Ad esempio, elaborando ひゃ, la libreria restituisce:
        - ひ
        - ゃ（や piccola）
        invece di riconoscere ひゃ come una sola sillaba composta.

        PT
        Tabela de Braille para a língua japonesa.
        Esta biblioteca utiliza o BrailleBase como base estrutural.
        A versão atual aceita chaves formadas por apenas um caractere japonês, enquanto os valores (brailles) podem conter quantas células forem necessárias.
        Observação:
        As combinações que formam yōon — como きゃ, きゅ, きょ, ひゃ, ひゅ, ひょ, ぴゃ, ぴゅ, ぴょ — são representadas no japonês por dois caracteres (por exemplo: ひ + ゃ = ひゃ).
        Como a versão atual só aceita chaves de um único caractere, essas combinações são interpretadas separadamente.
        Por exemplo, ao processar ひゃ, a biblioteca retorna:
        - ひ
        - ゃ（や pequena）
        em vez de reconhecer ひゃ como uma única unidade fonética.
        """
        super().__init__()
        #ひ
        self.append_braille_letter("あ", ["⠁"])
        self.append_braille_letter("い", ["⠃"])
        self.append_braille_letter("う", ["⠉"])
        self.append_braille_letter("え", ["⠋"])
        self.append_braille_letter("お", ["⠊"])
        self.append_braille_letter("か", ["⠡"])
        self.append_braille_letter("き", ["⠣"])
        self.append_braille_letter("く", ["⠩"])
        self.append_braille_letter("け", ["⠫"])
        self.append_braille_letter("こ", ["⠪"])
        self.append_braille_letter("さ", ["⠱"])
        self.append_braille_letter("し", ["⠳"])
        self.append_braille_letter("す", ["⠹"])
        self.append_braille_letter("せ", ["⠻"])
        self.append_braille_letter("そ", ["⠺"])
        self.append_braille_letter("た", ["⠕"])
        self.append_braille_letter("ち", ["⠗"])
        self.append_braille_letter("つ", ["⠝"])
        self.append_braille_letter("て", ["⠟"])
        self.append_braille_letter("と", ["⠞"])
        self.append_braille_letter("な", ["⠅"])
        self.append_braille_letter("に", ["⠇"])
        self.append_braille_letter("ぬ", ["⠍"])
        self.append_braille_letter("ね", ["⠏"])
        self.append_braille_letter("の", ["⠎"])
        self.append_braille_letter("は", ["⠥"])
        self.append_braille_letter("ひ", ["⠧"])
        self.append_braille_letter("ふ", ["⠭"])
        self.append_braille_letter("へ", ["⠯"])
        self.append_braille_letter("ほ", ["⠮"])
        self.append_braille_letter("ま", ["⠵"])
        self.append_braille_letter("み", ["⠷"])
        self.append_braille_letter("む", ["⠽"])
        self.append_braille_letter("め", ["⠿"])
        self.append_braille_letter("も", ["⠾"])
        self.append_braille_letter("や", ["⠌"])
        self.append_braille_letter("ゆ", ["⠬"])
        self.append_braille_letter("よ", ["⠜"])
        self.append_braille_letter("ら", ["⠑"])
        self.append_braille_letter("り", ["⠓"])
        self.append_braille_letter("る", ["⠙"])
        self.append_braille_letter("れ", ["⠛"])
        self.append_braille_letter("ろ", ["⠚"])
        self.append_braille_letter("わ", ["⠄"])
        self.append_braille_letter("ゐ", ["⠆"])
        self.append_braille_letter("ゑ", ["⠖"])
        self.append_braille_letter("を", ["⠔"])
        self.append_braille_letter("ん", ["⠴"])
        # 濁音
        self.append_braille_letter("が", ["⠐", "⠡"])
        self.append_braille_letter("ぎ", ["⠐", "⠣"])
        self.append_braille_letter("ぐ", ["⠐", "⠩"])
        self.append_braille_letter("げ", ["⠐", "⠫"])
        self.append_braille_letter("ご", ["⠐", "⠪"])
        self.append_braille_letter("ざ", ["⠐", "⠱"])
        self.append_braille_letter("じ", ["⠐", "⠳"])
        self.append_braille_letter("ず", ["⠐", "⠹"])
        self.append_braille_letter("ぜ", ["⠐", "⠻"])
        self.append_braille_letter("ぞ", ["⠐", "⠺"])
        self.append_braille_letter("だ", ["⠐", "⠕"])
        self.append_braille_letter("ぢ", ["⠐", "⠗"])
        self.append_braille_letter("づ", ["⠐", "⠝"])
        self.append_braille_letter("で", ["⠐", "⠟"])
        self.append_braille_letter("ど", ["⠐", "⠞"])
        self.append_braille_letter("ば", ["⠐", "⠥"])
        self.append_braille_letter("び", ["⠐", "⠧"])
        self.append_braille_letter("ぶ", ["⠐", "⠭"])
        self.append_braille_letter("べ", ["⠐", "⠯"])
        self.append_braille_letter("ぼ", ["⠐", "⠮"])
        # 半濁音
        self.append_braille_letter("ぱ", ["⠠", "⠥"])
        self.append_braille_letter("ぴ", ["⠠", "⠧"])
        self.append_braille_letter("ぷ", ["⠠", "⠭"])
        self.append_braille_letter("ぺ", ["⠠", "⠯"])
        self.append_braille_letter("ぽ", ["⠠", "⠮"])
        #拗音
        # きゃ きゅ きょ / ぎゃ ぎゅ ぎょ
        self.append_braille_letter("きゃ", ["⠣", "⠡"])
        self.append_braille_letter("きゅ", ["⠣", "⠣"])
        self.append_braille_letter("きょ", ["⠣", "⠩"])
        self.append_braille_letter("ぎゃ", ["⠐", "⠣", "⠡"])
        self.append_braille_letter("ぎゅ", ["⠐", "⠣", "⠣"])
        self.append_braille_letter("ぎょ", ["⠐", "⠣", "⠩"])
        # しゃ しゅ しょ / じゃ じゅ じょ
        self.append_braille_letter("しゃ", ["⠳", "⠡"])
        self.append_braille_letter("しゅ", ["⠳", "⠣"])
        self.append_braille_letter("しょ", ["⠳", "⠩"])
        self.append_braille_letter("じゃ", ["⠐", "⠳", "⠡"])
        self.append_braille_letter("じゅ", ["⠐", "⠳", "⠣"])
        self.append_braille_letter("じょ", ["⠐", "⠳", "⠩"])
        # ちゃ ちゅ ちょ / ぢゃ ぢゅ ぢょ
        self.append_braille_letter("ちゃ", ["⠗", "⠡"])
        self.append_braille_letter("ちゅ", ["⠗", "⠣"])
        self.append_braille_letter("ちょ", ["⠗", "⠩"])
        self.append_braille_letter("ぢゃ", ["⠐", "⠗", "⠡"])
        self.append_braille_letter("ぢゅ", ["⠐", "⠗", "⠣"])
        self.append_braille_letter("ぢょ", ["⠐", "⠗", "⠩"])
        # にゃ にゅ にょ
        self.append_braille_letter("にゃ", ["⠇", "⠡"])
        self.append_braille_letter("にゅ", ["⠇", "⠣"])
        self.append_braille_letter("にょ", ["⠇", "⠩"])
        # ひゃ ひゅ ひょ / びゃ びゅ びょ / ぴゃ ぴゅ ぴょ
        self.append_braille_letter("ひゃ", ["⠧", "⠡"])
        self.append_braille_letter("ひゅ", ["⠧", "⠣"])
        self.append_braille_letter("ひょ", ["⠧", "⠩"])
        self.append_braille_letter("びゃ", ["⠐", "⠧", "⠡"])
        self.append_braille_letter("びゅ", ["⠐", "⠧", "⠣"])
        self.append_braille_letter("びょ", ["⠐", "⠧", "⠩"])
        self.append_braille_letter("ぴゃ", ["⠠", "⠧", "⠡"])
        self.append_braille_letter("ぴゅ", ["⠠", "⠧", "⠣"])
        self.append_braille_letter("ぴょ", ["⠠", "⠧", "⠩"])
        # みゃ みゅ みょ
        self.append_braille_letter("みゃ", ["⠷", "⠡"])
        self.append_braille_letter("みゅ", ["⠷", "⠣"])
        self.append_braille_letter("みょ", ["⠷", "⠩"])
        # りゃ りゅ りょ
        self.append_braille_letter("りゃ", ["⠓", "⠡"])
        self.append_braille_letter("りゅ", ["⠓", "⠣"])
        self.append_braille_letter("りょ", ["⠓", "⠩"])

        self.append_braille_letter("ぁ", ["⠂", "⠁"])
        self.append_braille_letter("ぃ", ["⠂", "⠃"])
        self.append_braille_letter("ぅ", ["⠂", "⠉"])
        self.append_braille_letter("ぇ", ["⠂", "⠋"])
        self.append_braille_letter("ぉ", ["⠂", "⠊"])
        self.append_braille_letter("ゃ", ["⠂", "⠡"])
        self.append_braille_letter("ゅ", ["⠂", "⠣"])
        self.append_braille_letter("ょ", ["⠂", "⠩"])
        #促音
        self.append_braille_letter("っ", ["⠂", "⠝"])
        #長音 
        self.append_braille_letter("ー", ["⠒"])
        #number
        self.append_braille_letter("⠼", ["⠼"])
        self.append_braille_letter("1", ["⠁"])
        self.append_braille_letter("2", ["⠃"])
        self.append_braille_letter("3", ["⠉"])
        self.append_braille_letter("4", ["⠙"])
        self.append_braille_letter("5", ["⠑"])
        self.append_braille_letter("6", ["⠋"])
        self.append_braille_letter("7", ["⠛"])
        self.append_braille_letter("8", ["⠓"])
        self.append_braille_letter("9", ["⠊"])
        self.append_braille_letter("0", ["⠚"])
        # Simb
        self.append_braille_letter("。", ["⠲"])
        self.append_braille_letter("、", ["⠂"])
        self.append_braille_letter("・", ["⠂"])
        self.append_braille_letter("？", ["⠢"])
        self.append_braille_letter("！", ["⠖"])
        self.append_braille_letter(":", ["⠒"])
        self.append_braille_letter(";", ["⠆"])
        self.append_braille_letter("「", ["⠦"])
        self.append_braille_letter("」", ["⠴"])
        self.append_braille_letter("（", ["⠶"])
        self.append_braille_letter("）", ["⠶"])
        self.append_braille_letter("―", ["⠤"])
        self.append_braille_letter("-", ["⠤"])
        self.append_braille_letter("…", ["⠲", "⠲"])
        self.append_braille_letter(",", ["⠐", "⠂"])
        self.append_braille_letter(".", ["⠐", "⠲"])
        self.append_braille_letter("/", ["⠌"])
        self.append_braille_letter("／", ["⠌"])
        self.append_braille_letter("=", ["⠶"])
        self.append_braille_letter("¥", ["⠘", "⠽"])
        self.append_braille_letter("$", ["⠘", "⠎"])
        self.append_braille_letter("&", ["⠯"])
        self.append_braille_letter("@", ["⠈", "⠁"])
        self.append_braille_letter("#", ["⠼", "⠼"])
        self.append_braille_letter("＊", ["⠐", "⠔"])
        self.append_braille_letter("•", ["⠐", "⠂"])
        self.append_braille_letter("—", ["⠐", "⠤"])
        self.append_braille_letter("“", ["⠦"])
        self.append_braille_letter("”", ["⠴"])
        self.append_braille_letter("‘", ["⠦"])
        self.append_braille_letter("’", ["⠴"])
        self.append_braille_letter("°", ["⠘", "⠚"])
        self.append_braille_letter("≤", ["⠣", "⠶"])
        self.append_braille_letter("≥", ["⠜", "⠶"])
        self.append_braille_letter("≠", ["⠶", "⠐"])
        self.append_braille_letter("≈", ["⠐", "⠶"])
        self.append_braille_letter("∞", ["⠐", "⠪"])
        self.append_braille_letter("→", ["⠒", "⠕"])
        self.append_braille_letter("←", ["⠒", "⠣"])
        self.append_braille_letter("↑", ["⠒", "⠁"])
        self.append_braille_letter("↓", ["⠒", "⠉"])
        self.append_braille_letter("≡", ["⠶", "⠶"])
        self.append_braille_letter("~", ["⠐", "⠤"])
        self.append_braille_letter("|", ["⠸", "⠂"])
        self.append_braille_letter("⁂", ["⠐", "⠔", "⠐", "⠔", "⠐", "⠔"])
        self.append_braille_letter("〜", ["⠐", "⠤"])
        self.append_braille_letter("〃", ["⠐", "⠂"])
        self.append_braille_letter("™", ["⠘", "⠞"])
        self.append_braille_letter("©", ["⠘", "⠉"])
        self.append_braille_letter("®", ["⠘", "⠗"])
        self.append_braille_letter("↔", ["⠒", "⠕", "⠣"])
        self.append_braille_letter("↕", ["⠒", "⠁", "⠉"])
        #math
        self.append_braille_letter("+", ["⠖"])
        self.append_braille_letter("-", ["⠤"])
        self.append_braille_letter("*", ["⠔"])
        self.append_braille_letter("/", ["⠌"])
        self.append_braille_letter("=", ["⠶"])
        self.append_braille_letter("<", ["⠣"])
        self.append_braille_letter(">", ["⠜"])
        self.append_braille_letter("(", ["⠶"])
        self.append_braille_letter(")", ["⠶"])
        self.append_braille_letter("[", ["⠦"])
        self.append_braille_letter("]", ["⠴"])
        self.append_braille_letter("{", ["⠦"])
        self.append_braille_letter("}", ["⠴"])
        self.append_braille_letter("√", ["⠜", "⠱"])
        self.append_braille_letter("%", ["⠨", "⠴"])
        self.append_braille_letter("π", ["⠐", "⠏"])
        self.append_braille_letter("±", ["⠖", "⠤"])
        self.append_braille_letter("×", ["⠐", "⠔"])
        self.append_braille_letter("÷", ["⠐", "⠌"])
        self.append_braille_letter("∑", ["⠰", "⠎"])
        self.append_braille_letter("∫", ["⠰", "⠊"])
        self.append_braille_letter("∝", ["⠐", "⠒"])
        self.append_braille_letter("∈", ["⠰", "⠑"])
        self.append_braille_letter("∋", ["⠰", "⠓"])
        self.append_braille_letter("∪", ["⠰", "⠥"])
        self.append_braille_letter("∩", ["⠰", "⠉"])
        self.append_braille_letter("∧", ["⠰", "⠡"])
        self.append_braille_letter("∨", ["⠰", "⠣"])
        self.append_braille_letter("⇒", ["⠒", "⠕", "⠶"])
        self.append_braille_letter("⇔", ["⠒", "⠕", "⠒"])
        self.append_braille_letter("∞", ["⠐", "⠪"])
        self.append_braille_letter("≈", ["⠐", "⠶"])
        self.append_braille_letter("≠", ["⠶", "⠐"])
        self.append_braille_letter("≤", ["⠣", "⠶"])
        self.append_braille_letter("≥", ["⠜", "⠶"])
        #jus
        self.append_braille_letter("章", ["⠘", "⠗"])
        self.append_braille_letter("節", ["⠘", "⠎"])
        self.append_braille_letter("編", ["⠘", "⠓"])
        self.append_braille_letter("巻", ["⠘", "⠍"])
        self.append_braille_letter("第", ["⠘", "⠙"])
        self.append_braille_letter("条", ["⠘", "⠚"])
        self.append_braille_letter("項", ["⠘", "⠅"])
        self.append_braille_letter("号", ["⠘", "⠕"])
        self.append_braille_letter("々", ["⠐", "⠐"])
        self.append_braille_letter("§", ["⠘", "⠎"])
        self.append_braille_letter("¶", ["⠘", "⠏"])
        self.append_braille_letter("※", ["⠔"])
        self.append_braille_letter("∴", ["⠐", "⠲"])
        self.append_braille_letter("∵", ["⠐", "⠆"])
        self.append_braille_letter("〜", ["⠐", "⠤"])
        self.append_braille_letter("€", ["⠘", "⠑"])
        self.append_braille_letter("£", ["⠘", "⠇"])
        self.append_braille_letter("%", ["⠨", "⠴"])
        self.append_braille_letter("‰", ["⠨", "⠴", "⠴"])
        #music
        self.append_braille_letter("𝄞", ["⠈", "⠛"])
        self.append_braille_letter("𝄢", ["⠈", "⠋"])
        self.append_braille_letter("𝄡", ["⠈", "⠉"])
        self.append_braille_letter("♯", ["⠸", "⠩"])
        self.append_braille_letter("♭", ["⠸", "⠣"])
        self.append_braille_letter("♮", ["⠸", "⠿"])
        self.append_braille_letter("♩", ["⠈", "⠙"])
        self.append_braille_letter("♪", ["⠈", "⠙"])
        self.append_braille_letter("𝅘𝅥𝅮", ["⠼", "⠁", "⠚"])
        self.append_braille_letter("𝅘𝅥𝅯", ["⠼", "⠃", "⠚"])
        self.append_braille_letter("𝅘𝅥𝅰", ["⠼", "⠉", "⠚"])
        self.append_braille_letter("♫", ["⠈", "⠙", "⠈", "⠙"])
        self.append_braille_letter("♬", ["⠈", "⠙", "⠈", "⠙", "⠈", "⠙"])
        self.append_braille_letter("𝄽", ["⠈", "⠚"])
        self.append_braille_letter("𝄀", ["⠸", "⠂"])
        self.append_braille_letter("𝄁", ["⠸", "⠆"])
        self.append_braille_letter("𝄂", ["⠸", "⠒"])
        self.append_braille_letter("𝄪", ["⠸", "⠩", "⠩"])
        self.append_braille_letter("𝄫", ["⠸", "⠣", "⠣"])
        self.append_braille_letter("𝄆", ["⠸", "⠦"])
        self.append_braille_letter("𝄇", ["⠸", "⠴"])
        self.append_braille_letter("𝆗", ["⠈", "⠑"])
        self.append_braille_letter("𝆘", ["⠈", "⠓"])
        self.append_braille_letter("𝆙", ["⠈", "⠊"]) 
        self.append_braille_letter("𝆏", ["⠸", "⠉"])
        self.append_braille_letter("𝆐", ["⠸", "⠜"])
        self.append_braille_letter("𝄋", ["⠈", "⠎"])
        self.append_braille_letter("𝄌", ["⠈", "⠉", "⠙"])
        self.append_braille_letter("𝄐", ["⠈", "⠚"])
        self.append_braille_letter("𝄑", ["⠈", "⠚", "⠚"])
        self.append_braille_letter("𝄒", ["⠈", "⠚", "⠁"])
        self.append_braille_letter("𝄽", ["⠈", "⠚"])
        self.append_braille_letter("𝄾", ["⠈", "⠚", "⠂"])
        self.append_braille_letter("𝄿", ["⠈", "⠚", "⠆"])
        self.append_braille_letter("•", ["⠐", "⠂"])
        self.append_braille_letter("–", ["⠐", "⠤"])
        #self.append_braille_letter(">", ["⠐", "⠜"])
        # カタカナ
        self.append_special_braille_lettr_rules02("ア", ["⠁"])
        self.append_special_braille_lettr_rules02("イ", ["⠃"])
        self.append_special_braille_lettr_rules02("ウ", ["⠉"])
        self.append_special_braille_lettr_rules02("エ", ["⠋"])
        self.append_special_braille_lettr_rules02("オ", ["⠊"])
        self.append_special_braille_lettr_rules02("カ", ["⠡"])
        self.append_special_braille_lettr_rules02("キ", ["⠣"])
        self.append_special_braille_lettr_rules02("ク", ["⠩"])
        self.append_special_braille_lettr_rules02("ケ", ["⠫"])
        self.append_special_braille_lettr_rules02("コ", ["⠪"])
        self.append_special_braille_lettr_rules02("サ", ["⠱"])
        self.append_special_braille_lettr_rules02("シ", ["⠳"])
        self.append_special_braille_lettr_rules02("ス", ["⠹"])
        self.append_special_braille_lettr_rules02("セ", ["⠻"])
        self.append_special_braille_lettr_rules02("ソ", ["⠺"])
        self.append_special_braille_lettr_rules02("タ", ["⠕"])
        self.append_special_braille_lettr_rules02("チ", ["⠗"])
        self.append_special_braille_lettr_rules02("ツ", ["⠝"])
        self.append_special_braille_lettr_rules02("テ", ["⠟"])
        self.append_special_braille_lettr_rules02("ト", ["⠞"])
        self.append_special_braille_lettr_rules02("ナ", ["⠅"])
        self.append_special_braille_lettr_rules02("ニ", ["⠇"])
        self.append_special_braille_lettr_rules02("ヌ", ["⠍"])
        self.append_special_braille_lettr_rules02("ネ", ["⠏"])
        self.append_special_braille_lettr_rules02("ノ", ["⠎"])
        self.append_special_braille_lettr_rules02("ハ", ["⠥"])
        self.append_special_braille_lettr_rules02("ヒ", ["⠧"])
        self.append_special_braille_lettr_rules02("フ", ["⠭"])
        self.append_special_braille_lettr_rules02("ヘ", ["⠯"])
        self.append_special_braille_lettr_rules02("ホ", ["⠮"])
        self.append_special_braille_lettr_rules02("マ", ["⠵"])
        self.append_special_braille_lettr_rules02("ミ", ["⠷"])
        self.append_special_braille_lettr_rules02("ム", ["⠽"])
        self.append_special_braille_lettr_rules02("メ", ["⠿"])
        self.append_special_braille_lettr_rules02("モ", ["⠾"])
        self.append_special_braille_lettr_rules02("ヤ", ["⠌"])
        self.append_special_braille_lettr_rules02("ユ", ["⠬"])
        self.append_special_braille_lettr_rules02("ヨ", ["⠜"])
        self.append_special_braille_lettr_rules02("ラ", ["⠑"])
        self.append_special_braille_lettr_rules02("リ", ["⠓"])
        self.append_special_braille_lettr_rules02("ル", ["⠙"])
        self.append_special_braille_lettr_rules02("レ", ["⠛"])
        self.append_special_braille_lettr_rules02("ロ", ["⠚"])
        self.append_special_braille_lettr_rules02("ワ", ["⠄"])
        self.append_special_braille_lettr_rules02("ヰ", ["⠆"])
        self.append_special_braille_lettr_rules02("ヱ", ["⠖"])
        self.append_special_braille_lettr_rules02("ヲ", ["⠔"])
        self.append_special_braille_lettr_rules02("ン", ["⠴"])
        # カタカナ 濁音
        self.append_special_braille_lettr_rules02("ガ", ["⠐", "⠡"])
        self.append_special_braille_lettr_rules02("ギ", ["⠐", "⠣"])
        self.append_special_braille_lettr_rules02("グ", ["⠐", "⠩"])
        self.append_special_braille_lettr_rules02("ゲ", ["⠐", "⠫"])
        self.append_special_braille_lettr_rules02("ゴ", ["⠐", "⠪"])
        self.append_special_braille_lettr_rules02("ザ", ["⠐", "⠱"])
        self.append_special_braille_lettr_rules02("ジ", ["⠐", "⠳"])
        self.append_special_braille_lettr_rules02("ズ", ["⠐", "⠹"])
        self.append_special_braille_lettr_rules02("ゼ", ["⠐", "⠻"])
        self.append_special_braille_lettr_rules02("ゾ", ["⠐", "⠺"])
        self.append_special_braille_lettr_rules02("ダ", ["⠐", "⠕"])
        self.append_special_braille_lettr_rules02("ヂ", ["⠐", "⠗"])
        self.append_special_braille_lettr_rules02("ヅ", ["⠐", "⠝"])
        self.append_special_braille_lettr_rules02("デ", ["⠐", "⠟"])
        self.append_special_braille_lettr_rules02("ド", ["⠐", "⠞"])
        self.append_special_braille_lettr_rules02("バ", ["⠐", "⠥"])
        self.append_special_braille_lettr_rules02("ビ", ["⠐", "⠧"])
        self.append_special_braille_lettr_rules02("ブ", ["⠐", "⠭"])
        self.append_special_braille_lettr_rules02("ベ", ["⠐", "⠯"])
        self.append_special_braille_lettr_rules02("ボ", ["⠐", "⠮"])
        # カタカナ 半濁音
        self.append_special_braille_lettr_rules02("パ", ["⠠", "⠥"])
        self.append_special_braille_lettr_rules02("ピ", ["⠠", "⠧"])
        self.append_special_braille_lettr_rules02("プ", ["⠠", "⠭"])
        self.append_special_braille_lettr_rules02("ペ", ["⠠", "⠯"])
        self.append_special_braille_lettr_rules02("ポ", ["⠠", "⠮"])
        # カタカナ 拗音 (youon)
        # きゃ きゅ きょ / ぎゃ ぎゅ ぎょ
        self.append_special_braille_lettr_rules02("キャ", ["⠣", "⠡"])
        self.append_special_braille_lettr_rules02("キュ", ["⠣", "⠣"])
        self.append_special_braille_lettr_rules02("キョ", ["⠣", "⠩"])
        self.append_special_braille_lettr_rules02("ギャ", ["⠐", "⠣", "⠡"])
        self.append_special_braille_lettr_rules02("ギュ", ["⠐", "⠣", "⠣"])
        self.append_special_braille_lettr_rules02("ギョ", ["⠐", "⠣", "⠩"])
        # しゃ しゅ しょ / じゃ じゅ じょ
        self.append_special_braille_lettr_rules02("シャ", ["⠳", "⠡"])
        self.append_special_braille_lettr_rules02("シュ", ["⠳", "⠣"])
        self.append_special_braille_lettr_rules02("ショ", ["⠳", "⠩"])
        self.append_special_braille_lettr_rules02("ジャ", ["⠐", "⠳", "⠡"])
        self.append_special_braille_lettr_rules02("ジュ", ["⠐", "⠳", "⠣"])
        self.append_special_braille_lettr_rules02("ジョ", ["⠐", "⠳", "⠩"])
        # ちゃ ちゅ ちょ / ぢゃ ぢゅ ぢょ
        self.append_special_braille_lettr_rules02("チャ", ["⠗", "⠡"])
        self.append_special_braille_lettr_rules02("チュ", ["⠗", "⠣"])
        self.append_special_braille_lettr_rules02("チョ", ["⠗", "⠩"])
        self.append_special_braille_lettr_rules02("ヂャ", ["⠐", "⠗", "⠡"])
        self.append_special_braille_lettr_rules02("ヂュ", ["⠐", "⠗", "⠣"])
        self.append_special_braille_lettr_rules02("ヂョ", ["⠐", "⠗", "⠩"])
        # にゃ にゅ にょ
        self.append_special_braille_lettr_rules02("ニャ", ["⠇", "⠡"])
        self.append_special_braille_lettr_rules02("ニュ", ["⠇", "⠣"])
        self.append_special_braille_lettr_rules02("ニョ", ["⠇", "⠩"])
        # ひゃ ひゅ ひょ / びゃ びゅ びょ / ぴゃ ぴゅ ぴょ
        self.append_special_braille_lettr_rules02("ヒャ", ["⠧", "⠡"])
        self.append_special_braille_lettr_rules02("ヒュ", ["⠧", "⠣"])
        self.append_special_braille_lettr_rules02("ヒョ", ["⠧", "⠩"])
        self.append_special_braille_lettr_rules02("ビャ", ["⠐", "⠧", "⠡"])
        self.append_special_braille_lettr_rules02("ビュ", ["⠐", "⠧", "⠣"])
        self.append_special_braille_lettr_rules02("ビョ", ["⠐", "⠧", "⠩"])
        self.append_special_braille_lettr_rules02("ピャ", ["⠠", "⠧", "⠡"])
        self.append_special_braille_lettr_rules02("ピュ", ["⠠", "⠧", "⠣"])
        self.append_special_braille_lettr_rules02("ピョ", ["⠠", "⠧", "⠩"])
        # みゃ みゅ みょ
        self.append_special_braille_lettr_rules02("ミャ", ["⠷", "⠡"])
        self.append_special_braille_lettr_rules02("ミュ", ["⠷", "⠣"])
        self.append_special_braille_lettr_rules02("ミョ", ["⠷", "⠩"])
        # りゃ りゅ りょ
        self.append_special_braille_lettr_rules02("リャ", ["⠓", "⠡"])
        self.append_special_braille_lettr_rules02("リュ", ["⠓", "⠣"])
        self.append_special_braille_lettr_rules02("リョ", ["⠓", "⠩"])

        # Katakana small vowels
        self.append_special_braille_lettr_rules02("ァ", ["⠂", "⠁"])
        self.append_special_braille_lettr_rules02("ィ", ["⠂", "⠃"])
        self.append_special_braille_lettr_rules02("ゥ", ["⠂", "⠉"])
        self.append_special_braille_lettr_rules02("ェ", ["⠂", "⠋"])
        self.append_special_braille_lettr_rules02("ォ", ["⠂", "⠊"])

        # Katakana small ya/yu/yo
        self.append_special_braille_lettr_rules02("ャ", ["⠡"])
        self.append_special_braille_lettr_rules02("ュ", ["⠣"])
        self.append_special_braille_lettr_rules02("ョ", ["⠩"])
        # カタカナ #促音
        self.append_special_braille_lettr_rules02("ッ", ["⠂", "⠝"])

        # romanji
        self.append_braille_letter("a", ["⠁"])
        self.append_braille_letter("b", ["⠃"])
        self.append_braille_letter("c", ["⠉"])
        self.append_braille_letter("d", ["⠙"])
        self.append_braille_letter("e", ["⠑"])
        self.append_braille_letter("f", ["⠋"])
        self.append_braille_letter("g", ["⠛"])
        self.append_braille_letter("h", ["⠓"])
        self.append_braille_letter("i", ["⠊"])
        self.append_braille_letter("j", ["⠚"])
        self.append_braille_letter("k", ["⠅"])
        self.append_braille_letter("l", ["⠇"])
        self.append_braille_letter("m", ["⠍"])
        self.append_braille_letter("n", ["⠝"])
        self.append_braille_letter("o", ["⠕"])
        self.append_braille_letter("p", ["⠏"])
        self.append_braille_letter("q", ["⠟"])
        self.append_braille_letter("r", ["⠗"])
        self.append_braille_letter("s", ["⠎"])
        self.append_braille_letter("t", ["⠞"])
        self.append_braille_letter("u", ["⠥"])
        self.append_braille_letter("v", ["⠧"])
        self.append_braille_letter("w", ["⠺"]) 
        self.append_braille_letter("x", ["⠭"])
        self.append_braille_letter("y", ["⠽"])
        self.append_braille_letter("z", ["⠵"])
        
        self.append_special_braille_lettr_rules01("A", ["⠁"])
        self.append_special_braille_lettr_rules01("B", ["⠃"])
        self.append_special_braille_lettr_rules01("C", ["⠉"])
        self.append_special_braille_lettr_rules01("D", ["⠙"])
        self.append_special_braille_lettr_rules01("E", ["⠑"])
        self.append_special_braille_lettr_rules01("F", ["⠋"])
        self.append_special_braille_lettr_rules01("G", ["⠛"])
        self.append_special_braille_lettr_rules01("H", ["⠓"])
        self.append_special_braille_lettr_rules01("I", ["⠊"])
        self.append_special_braille_lettr_rules01("J", ["⠚"])
        self.append_special_braille_lettr_rules01("K", ["⠅"])
        self.append_special_braille_lettr_rules01("L", ["⠇"])
        self.append_special_braille_lettr_rules01("M", ["⠍"])
        self.append_special_braille_lettr_rules01("N", ["⠝"])
        self.append_special_braille_lettr_rules01("O", ["⠕"])
        self.append_special_braille_lettr_rules01("P", ["⠏"])
        self.append_special_braille_lettr_rules01("Q", ["⠟"])
        self.append_special_braille_lettr_rules01("R", ["⠗"])
        self.append_special_braille_lettr_rules01("S", ["⠎"])
        self.append_special_braille_lettr_rules01("T", ["⠞"])
        self.append_special_braille_lettr_rules01("U", ["⠥"])
        self.append_special_braille_lettr_rules01("V", ["⠧"])
        self.append_special_braille_lettr_rules01("W", ["⠺"])
        self.append_special_braille_lettr_rules01("X", ["⠭"])
        self.append_special_braille_lettr_rules01("Y", ["⠽"])
        self.append_special_braille_lettr_rules01("Z", ["⠵"])
