from braillebase import BrailleBase

class BrailleJapanese(BrailleBase):
    def __init__(self):

        """
        EN
        Braille table for the Japanese language.
        This library is built on top of BrailleBase.
        The current version accepts keys (characters) composed of only one Japanese character, while the values (braille cells) may contain as many cells as needed.
        Note:
        Combinations that form yōon — such as きゃ, きゅ, きょ, ひゃ, ひゅ, ひょ, ぴゃ, ぴゅ, ぴょ — are written in Japanese using two characters (for example: ひ + ゃ = ひゃ).
        Since the current version only accepts single‑character keys, these combinations are interpreted separately.
        For example, when processing ひゃ, the library outputs:
        - ひ
        - ゃ（small や）
        instead of recognizing ひゃ as a single combined syllable.

        JP
        日本語点字のテーブルです。
        このライブラリは BrailleBase を基盤として動作しています。
        現行バージョンでは、キー（文字）は 1 文字のみ登録でき、
        値（点字）は必要なだけ複数セルを登録できます。
        注意：
        **拗音（きゃ・きゅ・きょ、ひゃ・ひゅ・ひょ、ぴゃ・ぴゅ・ぴょ など）**は、
        本来 2 文字の組み合わせ（例：ひ + ゃ = ひゃ） で 1 音を表します。
        しかし現行バージョンでは キーが 1 文字しか登録できないため、
        「ひゃ」は次のように別々に処理されます：
        - ひ
        - ゃ（小さいや）
        つまり、ひゃ として 1 つの音にまとめることができません。

        IT
        Tabella Braille per la lingua giapponese.
        Questa libreria utilizza BrailleBase come struttura principale.
        L’attuale versione accetta chiavi composte da un solo carattere giapponese, mentre i valori (celle braille) possono contenere tutte le celle necessarie.
        Nota:
        Le combinazioni che formano gli yōon — come きゃ, きゅ, きょ, ひゃ, ひゅ, ひょ, ぴゃ, ぴゅ, ぴょ — sono scritte in giapponese usando due caratteri (ad esempio: ひ + ゃ = ひゃ).
        Poiché l’attuale versione accetta solo chiavi di un singolo carattere, queste combinazioni vengono interpretate separatamente.
        Ad esempio, elaborando ひゃ, la libreria restituisce:
        - ひ
        - ゃ（や piccola）
        invece di riconoscere ひゃ come una sola sillaba composta.

        PT
        Tabela de Braille para a língua japonesa.
        Esta biblioteca utiliza o BrailleBase como base estrutural.
        A versão atual aceita chaves formadas por apenas um caractere japonês, enquanto os valores (brailles) podem conter quantas células forem necessárias.
        Observação:
        As combinações que formam yōon — como きゃ, きゅ, きょ, ひゃ, ひゅ, ひょ, ぴゃ, ぴゅ, ぴょ — são representadas no japonês por dois caracteres (por exemplo: ひ + ゃ = ひゃ).
        Como a versão atual só aceita chaves de um único caractere, essas combinações são interpretadas separadamente.
        Por exemplo, ao processar ひゃ, a biblioteca retorna:
        - ひ
        - ゃ（や pequena）
        em vez de reconhecer ひゃ como uma única unidade fonética.
        """
        super().__init__()
        #ひ
        self.append_braille_letter("あ", ["⠁"])
        self.append_braille_letter("い", ["⠃"])
        self.append_braille_letter("う", ["⠉"])
        self.append_braille_letter("え", ["⠋"])
        self.append_braille_letter("お", ["⠊"])
        self.append_braille_letter("か", ["⠡"])
        self.append_braille_letter("き", ["⠣"])
        self.append_braille_letter("く", ["⠩"])
        self.append_braille_letter("け", ["⠫"])
        self.append_braille_letter("こ", ["⠪"])
        self.append_braille_letter("さ", ["⠱"])
        self.append_braille_letter("し", ["⠳"])
        self.append_braille_letter("す", ["⠹"])
        self.append_braille_letter("せ", ["⠻"])
        self.append_braille_letter("そ", ["⠺"])
        self.append_braille_letter("た", ["⠕"])
        self.append_braille_letter("ち", ["⠗"])
        self.append_braille_letter("つ", ["⠝"])
        self.append_braille_letter("て", ["⠟"])
        self.append_braille_letter("と", ["⠞"])
        self.append_braille_letter("な", ["⠅"])
        self.append_braille_letter("に", ["⠇"])
        self.append_braille_letter("ぬ", ["⠍"])
        self.append_braille_letter("ね", ["⠏"])
        self.append_braille_letter("の", ["⠎"])
        self.append_braille_letter("は", ["⠥"])
        self.append_braille_letter("ひ", ["⠧"])
        self.append_braille_letter("ふ", ["⠭"])
        self.append_braille_letter("へ", ["⠯"])
        self.append_braille_letter("ほ", ["⠮"])
        self.append_braille_letter("ま", ["⠵"])
        self.append_braille_letter("み", ["⠷"])
        self.append_braille_letter("む", ["⠽"])
        self.append_braille_letter("め", ["⠿"])
        self.append_braille_letter("も", ["⠾"])
        self.append_braille_letter("や", ["⠌"])
        self.append_braille_letter("ゆ", ["⠬"])
        self.append_braille_letter("よ", ["⠜"])
        self.append_braille_letter("ら", ["⠑"])
        self.append_braille_letter("り", ["⠓"])
        self.append_braille_letter("る", ["⠙"])
        self.append_braille_letter("れ", ["⠛"])
        self.append_braille_letter("ろ", ["⠚"])
        self.append_braille_letter("わ", ["⠄"])
        self.append_braille_letter("ゐ", ["⠆"])
        self.append_braille_letter("ゑ", ["⠖"])
        self.append_braille_letter("を", ["⠔"])
        self.append_braille_letter("ん", ["⠴"])
        #濁音
        self.append_braille_letter("が", ["⠐", "⠡"])
        self.append_braille_letter("ぎ", ["⠐", "⠣"])
        self.append_braille_letter("ぐ", ["⠐", "⠩"])
        self.append_braille_letter("げ", ["⠐", "⠫"])
        self.append_braille_letter("ご", ["⠐", "⠪"])
        self.append_braille_letter("ざ", ["⠐", "⠱"])
        self.append_braille_letter("じ", ["⠐", "⠳"])
        self.append_braille_letter("ず", ["⠐", "⠹"])
        self.append_braille_letter("ぜ", ["⠐", "⠻"])
        self.append_braille_letter("ぞ", ["⠐", "⠺"])
        self.append_braille_letter("だ", ["⠐", "⠕"])
        self.append_braille_letter("ぢ", ["⠐", "⠗"])
        self.append_braille_letter("づ", ["⠐", "⠝"])
        self.append_braille_letter("で", ["⠐", "⠟"])
        self.append_braille_letter("ど", ["⠐", "⠞"])
        self.append_braille_letter("ば", ["⠐", "⠥"])
        self.append_braille_letter("び", ["⠐", "⠧"])
        self.append_braille_letter("ぶ", ["⠐", "⠭"])
        self.append_braille_letter("べ", ["⠐", "⠯"])
        self.append_braille_letter("ぼ", ["⠐", "⠮"])
        #半濁音
        self.append_braille_letter("ぱ", ["⠠", "⠥"])
        self.append_braille_letter("ぴ", ["⠠", "⠧"])
        self.append_braille_letter("ぷ", ["⠠", "⠭"])
        self.append_braille_letter("ぺ", ["⠠", "⠯"])
        self.append_braille_letter("ぽ", ["⠠", "⠮"])
        #拗音
        # self.append_braille_letter("きゃ", ["⠈", "⠣"])
        # self.append_braille_letter("きゅ", ["⠘", "⠣"])
        # self.append_braille_letter("きょ", ["⠨", "⠣"])
        # self.append_braille_letter("ぎゃ", ["⠈", "⠐", "⠣"])
        # self.append_braille_letter("ぎゅ", ["⠘", "⠐", "⠣"])
        # self.append_braille_letter("ぎょ", ["⠨", "⠐", "⠣"])
        # self.append_braille_letter("しゃ", ["⠈", "⠳"])
        # self.append_braille_letter("しゅ", ["⠘", "⠳"])
        # self.append_braille_letter("しょ", ["⠨", "⠳"])
        # self.append_braille_letter("じゃ", ["⠈", "⠐", "⠳"])
        # self.append_braille_letter("じゅ", ["⠘", "⠐", "⠳"])
        # self.append_braille_letter("じょ", ["⠨", "⠐", "⠳"])
        # self.append_braille_letter("ちゃ", ["⠈", "⠗"])
        # self.append_braille_letter("ちゅ", ["⠘", "⠗"])
        # self.append_braille_letter("ちょ", ["⠨", "⠗"])
        # self.append_braille_letter("ぢゃ", ["⠈", "⠐", "⠗"])
        # self.append_braille_letter("ぢゅ", ["⠘", "⠐", "⠗"])
        # self.append_braille_letter("ぢょ", ["⠨", "⠐", "⠗"])
        # self.append_braille_letter("にゃ", ["⠈", "⠇"])
        # self.append_braille_letter("にゅ", ["⠘", "⠇"])
        # self.append_braille_letter("にょ", ["⠨", "⠇"])
        # self.append_braille_letter("ひゃ", ["⠈", "⠧"])
        # self.append_braille_letter("ひゅ", ["⠘", "⠧"])
        # self.append_braille_letter("ひょ", ["⠨", "⠧"])
        # self.append_braille_letter("びゃ", ["⠈", "⠐", "⠧"])
        # self.append_braille_letter("びゅ", ["⠘", "⠐", "⠧"])
        # self.append_braille_letter("びょ", ["⠨", "⠐", "⠧"])
        # self.append_braille_letter("ぴゃ", ["⠈", "⠠", "⠧"])
        # self.append_braille_letter("ぴゅ", ["⠘", "⠠", "⠧"])
        # self.append_braille_letter("ぴょ", ["⠨", "⠠", "⠧"])
        # self.append_braille_letter("みゃ", ["⠈", "⠷"])
        # self.append_braille_letter("みゅ", ["⠘", "⠷"])
        # self.append_braille_letter("みょ", ["⠨", "⠷"])
        # self.append_braille_letter("りゃ", ["⠈", "⠓"])
        # self.append_braille_letter("りゅ", ["⠘", "⠓"])
        # self.append_braille_letter("りょ", ["⠨", "⠓"])

        self.append_braille_letter("ぁ", ["⠂", "⠁"])
        self.append_braille_letter("ぃ", ["⠂", "⠃"])
        self.append_braille_letter("ぅ", ["⠂", "⠉"])
        self.append_braille_letter("ぇ", ["⠂", "⠋"])
        self.append_braille_letter("ぉ", ["⠂", "⠊"])
        self.append_braille_letter("ゃ", ["⠂", "⠌"])
        self.append_braille_letter("ゅ", ["⠂", "⠬"])
        self.append_braille_letter("ょ", ["⠂", "⠜"])
        #促音
        self.append_braille_letter("っ", ["⠂", "⠝"])
        #長音 
        self.append_braille_letter("ー", ["⠒"])
        #Simb
        self.append_braille_letter("。", ["⠲"])
        self.append_braille_letter("、", ["⠂"])
        self.append_braille_letter("・", ["⠂"])
        self.append_braille_letter("？", ["⠢"])
        self.append_braille_letter("！", ["⠖"])
        self.append_braille_letter(":", ["⠒"])
        self.append_braille_letter(";", ["⠆"])
        self.append_braille_letter("「", ["⠦"])
        self.append_braille_letter("」", ["⠴"])
        self.append_braille_letter("（", ["⠶"])
        self.append_braille_letter("）", ["⠶"])
        self.append_braille_letter("―", ["⠤"])  
        self.append_braille_letter("-", ["⠤"])   
        self.append_braille_letter("…", ["⠲", "⠲"])
        self.append_braille_letter(",", ["⠐", "⠂"])   
        self.append_braille_letter(".", ["⠐", "⠲"])   
        self.append_braille_letter("/", ["⠌"])
        self.append_braille_letter("=", ["⠶"])
        self.append_braille_letter("+", ["⠖"])
        self.append_braille_letter("-", ["⠤"])
        self.append_braille_letter("*", ["⠔"])
        self.append_braille_letter("/", ["⠌"])
        self.append_braille_letter("¥", ["⠘", "⠽"])
        self.append_braille_letter("$", ["⠘", "⠎"])
        self.append_braille_letter("&", ["⠯"])
        self.append_braille_letter("@", ["⠈", "⠁"])
        self.append_braille_letter("#", ["⠼", "⠼"])
        self.append_braille_letter("＊", ["⠐", "⠔"])
        self.append_braille_letter("•", ["⠐", "⠂"])
        self.append_braille_letter("—", ["⠐", "⠤"])
        self.append_braille_letter("“", ["⠦"])
        self.append_braille_letter("”", ["⠴"])
        self.append_braille_letter("‘", ["⠦"])
        self.append_braille_letter("’", ["⠴"])
        self.append_braille_letter("°", ["⠘", "⠚"])
        self.append_braille_letter("≤", ["⠣", "⠶"])
        self.append_braille_letter("≥", ["⠜", "⠶"])
        self.append_braille_letter("≠", ["⠶", "⠐"])
        self.append_braille_letter("≈", ["⠐", "⠶"])
        self.append_braille_letter("∞", ["⠐", "⠪"])
        self.append_braille_letter("→", ["⠒", "⠕"])
        self.append_braille_letter("←", ["⠒", "⠣"])
        self.append_braille_letter("↑", ["⠒", "⠁"])
        self.append_braille_letter("↓", ["⠒", "⠉"])
        self.append_braille_letter("≡", ["⠶", "⠶"])
        self.append_braille_letter("~", ["⠐", "⠤"])
        self.append_braille_letter("|", ["⠸", "⠂"])
        self.append_braille_letter("♪", ["⠈", "⠙"])
        self.append_braille_letter("♫", ["⠈", "⠙", "⠈", "⠙"])
        #number
        self.append_braille_letter("⠼", ["⠼"])
        self.append_braille_letter("1", ["⠁"])
        self.append_braille_letter("2", ["⠃"])
        self.append_braille_letter("3", ["⠉"])
        self.append_braille_letter("4", ["⠙"])
        self.append_braille_letter("5", ["⠑"])
        self.append_braille_letter("6", ["⠋"])
        self.append_braille_letter("7", ["⠛"])
        self.append_braille_letter("8", ["⠓"])
        self.append_braille_letter("9", ["⠊"])
        self.append_braille_letter("0", ["⠚"])
        #math
        self.append_braille_letter("+", ["⠖"])
        self.append_braille_letter("-", ["⠤"])
        self.append_braille_letter("*", ["⠔"])
        self.append_braille_letter("/", ["⠌"])
        self.append_braille_letter("=", ["⠶"])
        self.append_braille_letter("<", ["⠣"])
        self.append_braille_letter(">", ["⠜"])
        self.append_braille_letter("(", ["⠶"])
        self.append_braille_letter(")", ["⠶"])
        self.append_braille_letter("[", ["⠦"])
        self.append_braille_letter("]", ["⠴"])
        self.append_braille_letter("{", ["⠦"])
        self.append_braille_letter("}", ["⠴"])
        self.append_braille_letter("√", ["⠜"])
        self.append_braille_letter("%", ["⠨"])
        self.append_braille_letter("π", ["⠏"])
        # カタカナ
        self.append_braille_letter("ア", ["⠰", "⠁"])
        self.append_braille_letter("イ", ["⠰", "⠃"])
        self.append_braille_letter("ウ", ["⠰", "⠉"])
        self.append_braille_letter("エ", ["⠰", "⠋"])
        self.append_braille_letter("オ", ["⠰", "⠊"])
        self.append_braille_letter("カ", ["⠰", "⠡"])
        self.append_braille_letter("キ", ["⠰", "⠣"])
        self.append_braille_letter("ク", ["⠰", "⠩"])
        self.append_braille_letter("ケ", ["⠰", "⠫"])
        self.append_braille_letter("コ", ["⠰", "⠪"])
        self.append_braille_letter("サ", ["⠰", "⠱"])
        self.append_braille_letter("シ", ["⠰", "⠳"])
        self.append_braille_letter("ス", ["⠰", "⠹"])
        self.append_braille_letter("セ", ["⠰", "⠻"])
        self.append_braille_letter("ソ", ["⠰", "⠺"])
        self.append_braille_letter("タ", ["⠰", "⠕"])
        self.append_braille_letter("チ", ["⠰", "⠗"])
        self.append_braille_letter("ツ", ["⠰", "⠝"])
        self.append_braille_letter("テ", ["⠰", "⠟"])
        self.append_braille_letter("ト", ["⠰", "⠞"])
        self.append_braille_letter("ナ", ["⠰", "⠅"])
        self.append_braille_letter("ニ", ["⠰", "⠇"])
        self.append_braille_letter("ヌ", ["⠰", "⠍"])
        self.append_braille_letter("ネ", ["⠰", "⠏"])
        self.append_braille_letter("ノ", ["⠰", "⠎"])
        self.append_braille_letter("ハ", ["⠰", "⠥"])
        self.append_braille_letter("ヒ", ["⠰", "⠧"])
        self.append_braille_letter("フ", ["⠰", "⠭"])
        self.append_braille_letter("ヘ", ["⠰", "⠯"])
        self.append_braille_letter("ホ", ["⠰", "⠮"])
        self.append_braille_letter("マ", ["⠰", "⠵"])
        self.append_braille_letter("ミ", ["⠰", "⠷"])
        self.append_braille_letter("ム", ["⠰", "⠽"])
        self.append_braille_letter("メ", ["⠰", "⠿"])
        self.append_braille_letter("モ", ["⠰", "⠾"])
        self.append_braille_letter("ヤ", ["⠰", "⠌"])
        self.append_braille_letter("ユ", ["⠰", "⠬"])
        self.append_braille_letter("ヨ", ["⠰", "⠜"])
        self.append_braille_letter("ラ", ["⠰", "⠑"])
        self.append_braille_letter("リ", ["⠰", "⠓"])
        self.append_braille_letter("ル", ["⠰", "⠙"])
        self.append_braille_letter("レ", ["⠰", "⠛"])
        self.append_braille_letter("ロ", ["⠰", "⠚"])
        self.append_braille_letter("ワ", ["⠰", "⠄"])
        self.append_braille_letter("ヰ", ["⠰", "⠆"])
        self.append_braille_letter("ヱ", ["⠰", "⠖"])
        self.append_braille_letter("ヲ", ["⠰", "⠔"])
        self.append_braille_letter("ン", ["⠰", "⠴"])
        # カタカナ #濁音
        self.append_braille_letter("ガ", ["⠰", "⠐", "⠡"])
        self.append_braille_letter("ギ", ["⠰", "⠐", "⠣"])
        self.append_braille_letter("グ", ["⠰", "⠐", "⠩"])
        self.append_braille_letter("ゲ", ["⠰", "⠐", "⠫"])
        self.append_braille_letter("ゴ", ["⠰", "⠐", "⠪"])
        self.append_braille_letter("ザ", ["⠰", "⠐", "⠱"])
        self.append_braille_letter("ジ", ["⠰", "⠐", "⠳"])
        self.append_braille_letter("ズ", ["⠰", "⠐", "⠹"])
        self.append_braille_letter("ゼ", ["⠰", "⠐", "⠻"])
        self.append_braille_letter("ゾ", ["⠰", "⠐", "⠺"])
        self.append_braille_letter("ダ", ["⠰", "⠐", "⠕"])
        self.append_braille_letter("ヂ", ["⠰", "⠐", "⠗"])
        self.append_braille_letter("ヅ", ["⠰", "⠐", "⠝"])
        self.append_braille_letter("デ", ["⠰", "⠐", "⠟"])
        self.append_braille_letter("ド", ["⠰", "⠐", "⠞"])
        self.append_braille_letter("バ", ["⠰", "⠐", "⠥"])
        self.append_braille_letter("ビ", ["⠰", "⠐", "⠧"])
        self.append_braille_letter("ブ", ["⠰", "⠐", "⠭"])
        self.append_braille_letter("ベ", ["⠰", "⠐", "⠯"])
        self.append_braille_letter("ボ", ["⠰", "⠐", "⠮"])
        # カタカナ #半濁音
        self.append_braille_letter("パ", ["⠰", "⠠", "⠥"])
        self.append_braille_letter("ピ", ["⠰", "⠠", "⠧"])
        self.append_braille_letter("プ", ["⠰", "⠠", "⠭"])
        self.append_braille_letter("ペ", ["⠰", "⠠", "⠯"])
        self.append_braille_letter("ポ", ["⠰", "⠠", "⠮"])
        # カタカナ #拗音
        # self.append_braille_letter("キャ", ["⠰", "⠈", "⠣"])
        # self.append_braille_letter("キュ", ["⠰", "⠘", "⠣"])
        # self.append_braille_letter("キョ", ["⠰", "⠨", "⠣"])
        # self.append_braille_letter("ギャ", ["⠰", "⠈", "⠐", "⠣"])
        # self.append_braille_letter("ギュ", ["⠰", "⠘", "⠐", "⠣"])
        # self.append_braille_letter("ギョ", ["⠰", "⠨", "⠐", "⠣"])
        # self.append_braille_letter("シャ", ["⠰", "⠈", "⠳"])
        # self.append_braille_letter("シュ", ["⠰", "⠘", "⠳"])
        # self.append_braille_letter("ショ", ["⠰", "⠨", "⠳"])
        # self.append_braille_letter("ジャ", ["⠰", "⠈", "⠐", "⠳"])
        # self.append_braille_letter("ジュ", ["⠰", "⠘", "⠐", "⠳"])
        # self.append_braille_letter("ジョ", ["⠰", "⠨", "⠐", "⠳"])
        # self.append_braille_letter("チャ", ["⠰", "⠈", "⠗"])
        # self.append_braille_letter("チュ", ["⠰", "⠘", "⠗"])
        # self.append_braille_letter("チョ", ["⠰", "⠨", "⠗"])
        # self.append_braille_letter("ニャ", ["⠰", "⠈", "⠇"])
        # self.append_braille_letter("ニュ", ["⠰", "⠘", "⠇"])
        # self.append_braille_letter("ニョ", ["⠰", "⠨", "⠇"])
        # self.append_braille_letter("ヒャ", ["⠰", "⠈", "⠧"])
        # self.append_braille_letter("ヒュ", ["⠰", "⠘", "⠧"])
        # self.append_braille_letter("ヒョ", ["⠰", "⠨", "⠧"])
        # self.append_braille_letter("ビャ", ["⠰", "⠈", "⠐", "⠧"])
        # self.append_braille_letter("ビュ", ["⠰", "⠘", "⠐", "⠧"])
        # self.append_braille_letter("ビョ", ["⠰", "⠨", "⠐", "⠧"])
        # self.append_braille_letter("ピャ", ["⠰", "⠈", "⠠", "⠧"])
        # self.append_braille_letter("ピュ", ["⠰", "⠘", "⠠", "⠧"])
        # self.append_braille_letter("ピョ", ["⠰", "⠨", "⠠", "⠧"])
        # self.append_braille_letter("ミャ", ["⠰", "⠈", "⠷"])
        # self.append_braille_letter("ミュ", ["⠰", "⠘", "⠷"])
        # self.append_braille_letter("ミョ", ["⠰", "⠨", "⠷"])
        # self.append_braille_letter("リャ", ["⠰", "⠈", "⠓"])
        # self.append_braille_letter("リュ", ["⠰", "⠘", "⠓"])
        # self.append_braille_letter("リョ", ["⠰", "⠨", "⠓"])

        self.append_braille_letter("ァ", ["⠰", "⠂", "⠁"])
        self.append_braille_letter("ィ", ["⠰", "⠂", "⠃"])
        self.append_braille_letter("ゥ", ["⠰", "⠂", "⠉"])
        self.append_braille_letter("ェ", ["⠰", "⠂", "⠋"])
        self.append_braille_letter("ォ", ["⠰", "⠂", "⠊"])
        self.append_braille_letter("ャ", ["⠰", "⠈"])
        self.append_braille_letter("ュ", ["⠰", "⠘"])
        self.append_braille_letter("ョ", ["⠰", "⠨"])
        # カタカナ #促音
        self.append_braille_letter("ッ", ["⠰", "⠂", "⠝"])

        # romanji
        self.append_braille_letter("a", ["⠰", "⠁"])
        self.append_braille_letter("b", ["⠰", "⠃"])
        self.append_braille_letter("c", ["⠰", "⠉"])
        self.append_braille_letter("d", ["⠰", "⠙"])
        self.append_braille_letter("e", ["⠰", "⠑"])
        self.append_braille_letter("f", ["⠰", "⠋"])
        self.append_braille_letter("g", ["⠰", "⠛"])
        self.append_braille_letter("h", ["⠰", "⠓"])
        self.append_braille_letter("i", ["⠰", "⠊"])
        self.append_braille_letter("j", ["⠰", "⠚"])
        self.append_braille_letter("k", ["⠰", "⠅"])
        self.append_braille_letter("l", ["⠰", "⠇"])
        self.append_braille_letter("m", ["⠰", "⠍"])
        self.append_braille_letter("n", ["⠰", "⠝"])
        self.append_braille_letter("o", ["⠰", "⠕"])
        self.append_braille_letter("p", ["⠰", "⠏"])
        self.append_braille_letter("q", ["⠰", "⠟"])
        self.append_braille_letter("r", ["⠰", "⠗"])
        self.append_braille_letter("s", ["⠰", "⠎"])
        self.append_braille_letter("t", ["⠰", "⠞"])
        self.append_braille_letter("u", ["⠰", "⠥"])
        self.append_braille_letter("v", ["⠰", "⠧"])
        self.append_braille_letter("w", ["⠰", "⠺"])
        self.append_braille_letter("x", ["⠰", "⠭"])
        self.append_braille_letter("y", ["⠰", "⠽"])
        self.append_braille_letter("z", ["⠰", "⠵"])
        self.append_braille_letter("A", ["⠠", "⠰", "⠁"])
        self.append_braille_letter("B", ["⠠", "⠰", "⠃"])
        self.append_braille_letter("C", ["⠠", "⠰", "⠉"])
        self.append_braille_letter("D", ["⠠", "⠰", "⠙"])
        self.append_braille_letter("E", ["⠠", "⠰", "⠑"])
        self.append_braille_letter("F", ["⠠", "⠰", "⠋"])
        self.append_braille_letter("G", ["⠠", "⠰", "⠛"])
        self.append_braille_letter("H", ["⠠", "⠰", "⠓"])
        self.append_braille_letter("I", ["⠠", "⠰", "⠊"])
        self.append_braille_letter("J", ["⠠", "⠰", "⠚"])
        self.append_braille_letter("K", ["⠠", "⠰", "⠅"])
        self.append_braille_letter("L", ["⠠", "⠰", "⠇"])
        self.append_braille_letter("M", ["⠠", "⠰", "⠍"])
        self.append_braille_letter("N", ["⠠", "⠰", "⠝"])
        self.append_braille_letter("O", ["⠠", "⠰", "⠕"])
        self.append_braille_letter("P", ["⠠", "⠰", "⠏"])
        self.append_braille_letter("Q", ["⠠", "⠰", "⠟"])
        self.append_braille_letter("R", ["⠠", "⠰", "⠗"])
        self.append_braille_letter("S", ["⠠", "⠰", "⠎"])
        self.append_braille_letter("T", ["⠠", "⠰", "⠞"])
        self.append_braille_letter("U", ["⠠", "⠰", "⠥"])
        self.append_braille_letter("V", ["⠠", "⠰", "⠧"])
        self.append_braille_letter("W", ["⠠", "⠰", "⠺"])
        self.append_braille_letter("X", ["⠠", "⠰", "⠭"])
        self.append_braille_letter("Y", ["⠠", "⠰", "⠽"])
        self.append_braille_letter("Z", ["⠠", "⠰", "⠵"])
